antora:
  extensions:
    - '@springio/antora-extensions/partial-build-extension'
    - require: '@springio/antora-extensions/latest-version-extension'
    - require: '@springio/antora-extensions/inject-collector-cache-config-extension'
    - '@antora/collector-extension'
    - '@antora/atlas-extension'
    - require: '@springio/antora-extensions/root-component-extension'
      root_component_name: 'tracing'
site:
  title: Micrometer Tracing
  url: https://docs.micrometer.io/tracing/reference/
  robots: allow
content:
  sources:
    - url: https://github.com/micrometer-metrics/tracing
      # Refname matching: https://docs.antora.org/antora/latest/playbook/content-refname-matching/
      branches:
        - 'main'
        - '+({1..9}).+({0..9}).x' # 1.0.x and above
        - '!(1.{0..1}.x)' # Except 1.0.x and 1.1.x
      tags:
        - '+(v{1..9}).+({0..9}).+({0..9})?(-{RC,M}*)' # 1.0 and above
        - '!(v1.{0..1}.*)' # Except 1.0 and 1.1
        - '!(v1.2.0-{RC,M}*)' # Except 1.2 milestones/rc (1.2.0 is ok)
      start_path: docs
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/micrometer
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    chomp: 'all'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
  sourcemap: true
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
runtime:
  log:
    failure_level: warn
    format: pretty
ui:
  bundle:
    url: https://github.com/rwinch/antora-ui-micrometer/releases/download/latest/ui-bundle.zip
    snapshot: true
